name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: |
          flutter pub get
          # Explicitly install graphview package to ensure it's available
          flutter pub add graphview@1.2.0 --no-precompile
      
      - name: Verify formatting
        run: dart format --line-length 80 --set-exit-if-changed lib test
      
      - name: Analyze project source
        run: flutter analyze lib test
      
      - name: Run tests
        run: flutter test --coverage
